language: c

sudo: true

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - expect
      - lib64readline6-dev
      - libtool

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tcl-tk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force --overwrite tcl-tk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install readline; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p /usr/local; ln -s /usr/local/opt/tcl-tk/include /usr/local/include/tcl8.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp /usr/local/opt/tcl-tk/lib/libtcl* /usr/local/lib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/opt/tcl-tk/bin/tclsh8.6 /usr/local/bin/tclsh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/opt/tcl-tk/bin/tclsh8.6 /usr/local/bin/tclsh8.6; fi

script:
  - autoreconf -vif
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --with-readline-includes=/usr/local/Cellar/readline/7.0.3_1/include --with-readline-library=/usr/local/Cellar/readline/7.0.3_1/lib --with-tcl=/usr/local/lib; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /usr/bin/libtoolize --install; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /bin/sh -x ./autogen.sh; fi
  - make
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tclsh tests.tcl; fi
