language: c

sudo: true

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tcl-tk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force --overwrite tcl-tk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install readline; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y autoconf libtool automake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y tcl8.6-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y lib64readline6-dev; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then libtoolize --force --install; fi
  - autoreconf -vi
  - if [ -f /usr/local/lib/tclConfig.sh ]; then ./configure --with-readline-includes=/usr/local/Cellar/readline/7.0.3_1/include --with-readline-library=/usr/local/Cellar/readline/7.0.3_1/lib --with-tcl=/usr/local/lib; else ./configure; fi
  - make
  - sudo make install
